### ISSUE TITLE
No output

### ISSUE THREAD

**Issue by AndAShape** [h-kanazawa/react-detectable-overflow#4]
I have a table in an absolutely positioned div and the div is set to overflow-y. The vertical scroll bar on the div appears when the table is too long for the div.

Do I wrap the div in DetectableOverflow or should I _replace_ the div with DetectableOverflow?

Either way I'm getting no output from the component.

**Comment by h-kanazawa** [comment]
Current version, 0.2.0, supports only detecting overflow to horizontal direction. So some changes in this repository is required to detect vertical overflow.

Sorry, I need more information to investigate a cause of "no output". Could you show the code?

**Comment by h-kanazawa** [comment]
There are no replies for 1 year. So I close this.
