### ISSUE TITLE
errors in console when I run npm install react-detectable-overflow 

### ISSUE THREAD

**Issue by HawkeyePierce89** [h-kanazawa/react-detectable-overflow#87]
https://github.com/h-kanazawa/react-detectable-overflow/blob/7f42e75edf2487b980b9b9be27184fa996962eda/package.json#L21

```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'react-detectable-overflow@0.7.1',
npm WARN EBADENGINE   required: { node: '>=18' },
npm WARN EBADENGINE   current: { node: 'v16.20.2', npm: '8.19.4' }
npm WARN EBADENGINE }
```

**Comment by h-kanazawa** [comment]
This should be fixed in version 0.7.2.
https://github.com/h-kanazawa/react-detectable-overflow/commit/37daa7987d6277e293d81f20f40114c4c1a3bd64
